[project]
name = "odoo-addons-akretion-snjb"
version = "18.0.20250130.0"
dependencies = [
    "odoo-addon-base_c==18.0.*",
    "odoo-addon-optional_c==18.0.*",
    "odoo-addon-product_pricelist_supplierinfo_category==18.0.*",
    "odoo-addon-record_field_log==18.0.*",
    "odoo-addon-report_c==18.0.*",
    "odoo-addon-sale_deliver_service_as_goods==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
